# Generated by Django 3.0.8 on 2021-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211013_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='postmedia',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='posttag',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
