# Generated by Django 3.0.8 on 2021-10-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='post_id',
        ),
    ]
