# Generated by Django 3.0.8 on 2021-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modify_date',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to='file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
