# Generated by Django 3.0.8 on 2021-10-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211006_1547'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posthashtag',
            table='post_hashtag',
        ),
    ]
