# Generated by Django 3.0.8 on 2021-10-11 05:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211005_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_time',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_time',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 11, 5, 23, 18, 756880, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 11, 5, 23, 45, 341800, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex'), ('N', 'Not_listed')], max_length=2),
        ),
    ]
