# Generated by Django 3.0.8 on 2021-10-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211006_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commenthashtag',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commenthashtag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comments_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commenttag',
            old_name='comments_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commenttag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posthashtag',
            old_name='hashtag_id',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='posthashtag',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posttag',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posttag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='post_id',
            new_name='post',
        ),
    ]
