# Generated by Django 3.0.8 on 2021-10-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('여성', '여성'), ('남성', '남성')], max_length=10),
        ),
    ]
