# Generated by Django 3.0.8 on 2021-11-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_from',
            new_name='userFrom',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_to',
            new_name='userTo',
        ),
    ]
