# Generated by Django 3.0.8 on 2021-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20211007_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='post'),
        ),
    ]
