# Generated by Django 3.0.8 on 2021-10-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtag', '0001_initial'),
        ('post', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtagpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='hashtagcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag', to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='hashtagcomment',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_hashtag', to='hashtag.Hashtag'),
        ),
    ]
