# Generated by Django 3.0.8 on 2021-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_auto_20211013_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='hashtagcomment',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='hashtagpost',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
