# Generated by Django 3.0.8 on 2021-10-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='email',
        ),
    ]
