# Generated by Django 3.0.8 on 2021-10-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
